name: Build and Deploy Adapt Course

on:
  push:
    branches:
      - main  # Set this to your default branch

permissions:
  contents: write # Needed to push the build to the gh-pages branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Use 14 or 16 for maximum compatibility

      - name: Install Global Dependencies
        run: |
          npm install -g grunt-cli
          npm install -g adapt-cli

      - name: Create and Install Course
        # This creates the course and installs its internal dependencies
        run: |
          cd src/course
          npm install 
       #   adapt help create
       #   adapt create course my-test-course .
       #   cd my-test-course


      - name: Build Course
        #working-directory: ./my-test-course
        working-directory: ./src/course
        run: grunt build --languages=en

      # 6. Deploy to GitHub Pages
      # This takes the contents of the /build folder and pushes it to a gh-pages branch
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build # The directory the action will deploy
          branch: gh-pages # The branch the action will deploy to
