name: Build and Deploy Adapt Course

on:
  push:
    branches:
      - main  

permissions:
  contents: write # Needed to push the build to the gh-pages branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*' 

      - name: Install Global Dependencies
        run: |
          npm ci
          npx -y -p grunt-cli adapt-cli adapt install
          #npm install -g grunt-cli
          #npm install -g adapt-cli

      #- name: Install Project Dependencies
        # Run this at the root to install Grunt plugins defined in package.json
     #   run: npm install 

    #  - name: Install Adapt Plugins
        # Run this at the root to download components/extensions/themes into src/
    #    run: adapt install

      - name: Build Course
        # Run at the root. Removed the working-directory parameter.
        run: grunt build --languages=en --verbose

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build 
          branch: gh-pages
